import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/shared/Slices/Provider";
// import { Provider } from "react-redux";
// import store from "@/core/store";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>

        {children}
        </Providers>
      </body>
    </html>
  );
}
